[build]
	functions = "functions/"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
	Access-Control-Allow-Methods = "GET,HEAD,OPTIONS,POST,PUT"
	Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"

[context.development]
	[context.development.environment]
		GATSBY_GRAPHQL_API = "https://dev.api.withfriends.co/graphql"
		GATSBY_PUBLIC_JWT = "eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImFkbWluIjpmYWxzZX0sInN1YiI6bnVsbCwiZXhwIjoxNjQwMjg5NjEzfQ.GAuQYAcnTpUjMtKsQurCCMLCRQMXQtF7_jQE5jAoqXU"
		GATSBY_FB_APP_ID = "769110557146959"
		GATSBY_FB_REDIRECT_URI = "https://dev.why.withfriends.co/.netlify/functions/facebook_login"
		BASE_URL = "https://dev.why.withfriends.co/organizers"
		FB_APP_SECRET = "ba7389e45d29318095818bee3c82b3b3"
		ADMIN_JWT = "eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImFkbWluIjp0cnVlfSwic3ViIjpudWxsLCJleHAiOjE2NDE0OTM4NjB9.4qJacegECnM6koLJAcJQuaYYIiF3BHeHMlKf5uSCvsc"

[context.staging]
	[context.staging.environment]
		GATSBY_GRAPHQL_API = "https://wf-graphql-api-staging.herokuapp.com"
		GATSBY_PUBLIC_JWT = "eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImFkbWluIjpmYWxzZX0sInN1YiI6bnVsbCwiZXhwIjoxNjQwMjAwMjIzfQ.ozhMygzdz7nUxcFcpdDmiCOZHxqhil3MelCpa_8dMl4"
		GATSBY_FB_APP_ID = "769110557146959"
		GATSBY_FB_REDIRECT_URI = "https://sandbox-why.withfriends.co/.netlify/functions/facebook_login"
		BASE_URL = "https://sandbox-why.withfriends.co/organizers"
		FB_APP_SECRET = "ba7389e45d29318095818bee3c82b3b3"

[context.production]
	[context.production.environment]
		GATSBY_GRAPHQL_API = "https://wf-graphql-api.herokuapp.com"
		GATSBY_PUBLIC_JWT = "eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImFkbWluIjpmYWxzZX0sInN1YiI6bnVsbCwiZXhwIjoxNjQwMjAwMzIwfQ.XMtCGoGk9peJnph25V7CirtXZiMMP6-KZejlF2qWIUQ"
		GATSBY_FB_APP_ID = "783700495040097"
		GATSBY_FB_REDIRECT_URI = "https://why.withfriends.co/.netlify/functions/facebook_login"
		BASE_URL = "https://why.withfriends.co/organizers"
		FB_APP_SECRET = "eaaa0814c6979846f63ccfee3f05c0fa"
		ADMIN_JWT = "eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImFkbWluIjp0cnVlfSwic3ViIjpudWxsLCJleHAiOjE5MjYwMTI4NTB9.deQVAbZOLnEI3eZgl3wGBok4hUEQCQ0YJyxxagG0LZs"

