[context.production]
	[context.production.environment]
		GATSBY_GRAPHQL_API = "https://wf-graphql-api.herokuapp.com"
		GATSBY_PUBLIC_JWT = "eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImFkbWluIjpmYWxzZX0sInN1YiI6bnVsbCwiZXhwIjoxNjQwMjAwMzIwfQ.XMtCGoGk9peJnph25V7CirtXZiMMP6-KZejlF2qWIUQ"

[context.staging]
	[context.staging.environment]
		GATSBY_GRAPHQL_API = "https://wf-graphql-api-staging.herokuapp.com"
		GATSBY_PUBLIC_JWT = "eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImFkbWluIjpmYWxzZX0sInN1YiI6bnVsbCwiZXhwIjoxNjQwMjAwMjIzfQ.ozhMygzdz7nUxcFcpdDmiCOZHxqhil3MelCpa_8dMl4"

