[build]
	functions = "functions/"

[context.development]
	[context.development.environment]
		GATSBY_GRAPHQL_API = "http://localhost:4002/graphql"
		GATSBY_PUBLIC_JWT = "eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImFkbWluIjpmYWxzZX0sInN1YiI6bnVsbCwiZXhwIjoxNjQwMjg5NjEzfQ.GAuQYAcnTpUjMtKsQurCCMLCRQMXQtF7_jQE5jAoqXU"
		GATSBY_FB_APP_ID = "769110557146959"
		GATSBY_FB_REDIRECT_URI = "http://localhost:8000/.netlify/functions/facebook_login"
		BASE_URL = "http://localhost:8000"
		GATSBY_JELLY_URL = "https://dev.better.space"
		FB_APP_SECRET = "ba7389e45d29318095818bee3c82b3b3"
		ADMIN_JWT = "eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImFkbWluIjp0cnVlfSwic3ViIjpudWxsLCJleHAiOjE2NDQ5NjM1MTR9.iwSDjX_KALtsT83u6prvQbv9ZQa8HBuEPjIf0VtXfAI"
		GATSBY_MIXPANEL_KEY = "287044101a1f47c209745cab2afcbb0e"

[context.staging]
	[context.staging.environment]
		GATSBY_GRAPHQL_API = "https://wf-graphql-api-staging.herokuapp.com"
		GATSBY_PUBLIC_JWT = "eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImFkbWluIjpmYWxzZX0sInN1YiI6bnVsbCwiZXhwIjoxNjQwMjAwMjIzfQ.ozhMygzdz7nUxcFcpdDmiCOZHxqhil3MelCpa_8dMl4"
		GATSBY_FB_APP_ID = "769110557146959"
		GATSBY_FB_REDIRECT_URI = "https://sandbox-why.withfriends.co/.netlify/functions/facebook_login"
		BASE_URL = "https://sandbox-why.withfriends.co"
		GATSBY_JELLY_URL = "https://staging.withfriends.cool"
		FB_APP_SECRET = "ba7389e45d29318095818bee3c82b3b3"
		GATSBY_MIXPANEL_KEY = "287044101a1f47c209745cab2afcbb0e"

[context.production]
	[context.production.environment]
		GATSBY_GRAPHQL_API = "https://wf-graphql-api.herokuapp.com"
		GATSBY_PUBLIC_JWT = "eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImFkbWluIjpmYWxzZX0sInN1YiI6bnVsbCwiZXhwIjoxNjQwMjAwMzIwfQ.XMtCGoGk9peJnph25V7CirtXZiMMP6-KZejlF2qWIUQ"
		GATSBY_FB_APP_ID = "783700495040097"
		GATSBY_FB_REDIRECT_URI = "https://why.withfriends.co/.netlify/functions/facebook_login"
		BASE_URL = "https://why.withfriends.co"
		GATSBY_JELLY_URL = "https://withfriends.co"
		FB_APP_SECRET = "eaaa0814c6979846f63ccfee3f05c0fa"
		ADMIN_JWT = "eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImFkbWluIjp0cnVlfSwic3ViIjpudWxsLCJleHAiOjE5MjYwMTI4NTB9.deQVAbZOLnEI3eZgl3wGBok4hUEQCQ0YJyxxagG0LZs"
		GATSBY_MIXPANEL_KEY = "5c91cd64f52c6452741c98f5e6615923"

